-- 1
SELECT A.* FROM CLIENTE A
WHERE A.ID_CLIENTE IN (
  SELECT B.ID_CLIENTE FROM PEDIDO
  WHERE FECHA_ENVIO BETWEEN '2022-01-01' AND '2022-01-01';
)
-- 2
SELECT B.ID_PRODUCTO, A.NOMBRE, A.STOCK, A.PRECIO_VENTA, A.SUCURSAL COUNT(B.ID_PRODUCTO) AS OCURRENCIAS
FROM PRODUCTO A, DETALLE_PEDIDO B
AND B.ID_PRODUCTO = A.ID_PRODUCTO 
GROUP BY B.ID_PRODUCTO ORDER BY OCURRENCIAS DESC LIMIT 1;
-- 3
SELECT A.* FROM VENDEDOR A
WHERE A.ID_VENDEDOR NOT IN (
  SELECT B.ID_VENDEDOR FROM PEDIDO
  WHERE FECHA_ENVIO = '2022-01-01';
)
-- 4
SELECT A.* FROM CLIENTE A
WHERE A.ID_CLIENTE NOT IN (
  SELECT B.ID_CLIENTE FROM PEDIDO
  WHERE FECHA_ENVIO = '2022-01-01';
)
-- 5
SELECT 
  A.FECHA_NACIMIENTO
 ,FLOOR(DATEDIFF(dd,A.FECHA_NACIMIENTO,GETDATE()) / 365.25) AS EDAD_AHORA
 ,FLOOR(DATEDIFF(dd,A.FECHA_NACIMIENTO,GETDATE()+30) / 365.25) AS EDAD_EN_30_DIAS
FROM 
  CLIENTE A
WHERE 1 = (FLOOR(DATEDIFF(dd,A.FECHA_NACIMIENTO,GETDATE()+30) / 365.25))
          -
          (FLOOR(DATEDIFF(dd,A.FECHA_NACIMIENTO,GETDATE()) / 365.25))